---
permalink: rhel-install/reference-system-requirements-for-oncommand-workflow-automation-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, system, requirements, install, hardware, requirements, install, wfa 
summary: 'Vor der Installation von WFA müssen Sie die Hardware- und Software-Anforderungen des OnCommand Workflow Automation (WFA) kennen.' 
---
= Systemanforderungen für die Installation von OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation von WFA müssen Sie die Hardware- und Software-Anforderungen des OnCommand Workflow Automation (WFA) kennen.



== Hardwareanforderungen für die Installation von WFA

In der folgenden Tabelle sind die Mindestanforderungen an die Hardware und die empfohlenen Hardwarespezifikationen für den WFA Server aufgeführt.

[cols="3*"]
|===
| Komponente | Mindestanforderungen | Empfohlene Spezifikationen 


 a| 
CPU
 a| 
2.27 GHz oder schneller, 2 Kerne, 64 Bit
 a| 
2.27 GHz oder schneller, 2 Kerne, 64 Bit



 a| 
RAM
 a| 
4 GB
 a| 
8 GB



 a| 
Freier Speicherplatz
 a| 
5 GB
 a| 
20 GB

|===
[NOTE]
====
Wenn Sie WFA auf einer Virtual Machine (VM) installieren, sollten Sie den erforderlichen Arbeitsspeicher und die erforderliche CPU reservieren, damit die VM über ausreichende Ressourcen verfügt. Der Installer überprüft nicht die CPU-Geschwindigkeit.

====


== Softwareanforderungen für die Installation von WFA

In der folgenden Tabelle sind alle mit dem WFA Server kompatiblen Betriebssystemversionen aufgeführt.

[cols="2*"]
|===
| Betriebssystem | Version 


 a| 
Red Hat Enterprise Linux
 a| 
6.5, 7.0, 7.1 64-Bit-Betriebssysteme, 7.2, 7.3 und 7.4



 a| 
CentOS
 a| 
7.1, 7.2 und 7.3

|===
[NOTE]
====
WFA sollte auf dedizierten physischen Computern oder VMs installiert werden. Sie dürfen keine anderen Anwendungen auf dem Server installieren, auf dem WFA ausgeführt wird.

====


== Sonstige erforderliche Mindestsoftware

* Einer der folgenden unterstützten Browser:
+
** Mozilla Firefox
** Microsoft Internet Explorer
** Google Chrome


* Die neueste Version von Adobe Flash Player für Ihren Browser
* Perl v5.10.1
+
Sie erhalten Informationen über die Perl-Module, die über die installiert werden sollen `./WFA-version_number.bin -l` Befehl.



Weitere Informationen finden Sie im Interoperabilitäts-Matrix-Tool.

*Verwandte Informationen*

http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^]
