---
permalink: rhel-install/task-back-up-full-the-wfa-database-using-perl-script-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, backup, wfa, database, cli 
summary: 'Sie können ein vollständiges Backup der WFA-Datenbank (OnCommand Workflow Automation) über die WFA-Befehlszeilenschnittstelle (CLI) durchführen. In einem vollständigen Backup werden die WFA Datenbank, die WFA Konfiguration und der Schlüssel gesichert.' 
---
= Sichern Sie die WFA Datenbank mithilfe der CLI (vollständig)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein vollständiges Backup der WFA-Datenbank (OnCommand Workflow Automation) über die WFA-Befehlszeilenschnittstelle (CLI) durchführen. In einem vollständigen Backup werden die WFA Datenbank, die WFA Konfiguration und der Schlüssel gesichert.

.Was Sie benötigen
Sie müssen über Anmeldedaten für Admin-Benutzer oder Systemarchitekten verfügen.

.Über diese Aufgabe
In einer Hochverfügbarkeitsumgebung sollten geplante Backups mithilfe VON REST APIs erstellt werden. Sie können keine Backups über die CLI erstellen, wenn WFA sich im Failover-Modus befindet.

Weitere Informationen finden Sie in DER REST-Dokumentation.

.Schritte
. Navigieren Sie an der Shell-Eingabeaufforderung zum folgenden Verzeichnis auf dem WFA Server:
+
`WFA_install_location/wfa/bin/.`

+
`WFA_install_location` Ist das WFA Installationsverzeichnis.

. Backup der WFA Datenbank:
+
`.\wfa --backup --user=USER [--password=PASS] [--location=PATH] [--full]`

+
** _User_ ist der Benutzername des Backup-Benutzers.
** _Password_ ist das Passwort des Backup-Benutzers.
+
Falls Sie kein Passwort angegeben haben, müssen Sie das Passwort eingeben, wenn Sie dazu aufgefordert werden.

** _Path_ ist der vollständige Verzeichnispfad zur Sicherungsdatei.


. *Optional:* Überprüfen Sie, ob die Sicherungsdatei am angegebenen Speicherort erstellt wurde.

