---
permalink: rhel-install/task-modify-the-default-password-policy-linux.html 
sidebar: sidebar 
keywords: modify, default, password, policy 
summary: 'OnCommand Workflow Automation (WFA) ist so konfiguriert, dass eine Passwortrichtlinie für lokale Benutzer durchgesetzt wird. Sie können die Standard-Passwortrichtlinie ändern.' 
---
= Ändern Sie die Standard-Kennwortrichtlinie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) ist so konfiguriert, dass eine Passwortrichtlinie für lokale Benutzer durchgesetzt wird. Sie können die Standard-Passwortrichtlinie ändern.

.Was Sie benötigen
Sie müssen sich als Root-Benutzer beim WFA Host-System angemeldet haben.

.Über diese Aufgabe
* In diesem Verfahren wird der WFA Standardinstallationspfad verwendet.
+
Wenn Sie während der Installation den Standardspeicherort geändert haben, müssen Sie den geänderten WFA Installationspfad verwenden.

* Der Befehl für die Standard-Passwortrichtlinie lautet `./wfa --password-policy=default`.
+
Der Standardwert ist "`minLength=true,6;specialChar=true,1;digitalChar=true,1;lowercaseChar=true,1;uppercaseChar=true,1;whespaceChar=false`".

+
Dies bedeutet, dass die Standard-Passwortrichtlinie eine Mindestlänge von 6 Zeichen haben muss und mindestens 1 Sonderzeichen, 1 Ziffer, 1 Kleinbuchstaben, 1 Großbuchstaben und keine Leerzeichen enthalten muss.



.Schritte
. Navigieren Sie an der Shell-Eingabeaufforderung zum folgenden Verzeichnis auf dem WFA Server:
+
`WFA_install_location/wfa/bin/`

. Ändern Sie die Standard-Passwortrichtlinie durch Eingabe des folgenden Befehls:
+
`./wfa --password-policy=PasswordPolicyString --restart=WFA`


