---
permalink: windows-install/task-regular-restore-of-the-oncommand-workflow-automation-database-using-clis-windows.html 
sidebar: sidebar 
keywords: oncommand workflow automation, restore, regular, wfa, database, cli 
summary: 'Sie können die OnCommand Workflow Automation (WFA) Datenbank regelmäßig wiederherstellen, indem Sie die REST-APIs verwenden. In einer normalen Wiederherstellung kann nur eine Sicherung der WFA Datenbank durchgeführt werden.' 
---
= Stellen Sie mithilfe der CLI eine (normale) WFA Datenbank wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die OnCommand Workflow Automation (WFA) Datenbank regelmäßig wiederherstellen, indem Sie die REST-APIs verwenden. In einer normalen Wiederherstellung kann nur eine Sicherung der WFA Datenbank durchgeführt werden.

.Was Sie benötigen
* Sie müssen ein Backup der WFA Datenbank erstellt haben.
* Sie müssen über Administratoranmeldeinformationen, Anmeldedaten für den Systemarchitekten oder Anmeldedaten für den Backup-Benutzer verfügen.


.Schritte
. Navigieren Sie an der Shell-Eingabeaufforderung zum folgenden Verzeichnis auf dem WFA Server:
+
`WFA_install_location\WFA\bin`

+
`wfa_install_location` Ist das WFA Installationsverzeichnis.

. Führen Sie den Wiederherstellungsvorgang aus:
+
`wfa.cmd --restore --user=user_name [--password=password] [--location=path]`

+
** _User_Name_ ist der Benutzername des Admin- oder Architect-Benutzers.
** _Password_ ist das Passwort des Benutzers.
+
Falls Sie kein Passwort angegeben haben, müssen Sie das Passwort eingeben, wenn Sie dazu aufgefordert werden.

** _Path_ ist der vollständige Verzeichnispfad zur Wiederherstellungsdatei.


. Vergewissern Sie sich, dass der Wiederherstellungsvorgang erfolgreich ist und WFA zugänglich ist.

