---
permalink: windows-install/task-configure-a-database-user-by-running-ocsetup-on-linux.html 
sidebar: sidebar 
keywords: configure, database, user, running, ocsetup, linux 
summary: Sie können die ocsetup-Datei auf dem Active IQ Datacenter Manager-Server ausführen, um den schreibgeschützten Zugriff der Active IQ Datacenter Manager-Datenbank auf OnCommand Workflow Automation zu konfigurieren. 
---
= Konfigurieren Sie einen Datenbankbenutzer, indem Sie ocsetup unter Linux ausführen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die ocsetup-Datei auf dem Active IQ Datacenter Manager-Server ausführen, um den schreibgeschützten Zugriff der Active IQ Datacenter Manager-Datenbank auf OnCommand Workflow Automation zu konfigurieren.

.Schritte
. Laden Sie die herunter `wfa_ocsetup.sh` Datei in Ihr Home-Verzeichnis auf dem Active IQ-Rechenzentrumsmanager-Server mit dem folgenden Befehl im Terminal: `+wget https://WFA_Server_IP/download/wfa_ocsetup.sh+`
+
`WFA_Server_IP` Ist die IP-Adresse (IPv4 oder IPv6-Adresse) des WFA Servers.

+
Wenn Sie einen nicht-Standardport für WFA angegeben haben, müssen Sie die Portnummer wie folgt angeben:

+
`+wget https://wfa_server_ip:port/download/wfa_ocsetup.sh+`

+
_Port_ ist die TCP-Portnummer, die Sie bei der Installation für den WFA Server verwendet haben.

+
Wenn Sie eine IPv6-Adresse angeben, müssen Sie sie mit eckigen Klammern schließen.

. Verwenden Sie den folgenden Befehl im Terminal, um die Datei wfa_ocsetup.sh in eine ausführbare Datei zu ändern:
+
`chmod +x wfa_ocsetup.sh`

. Führen Sie das Skript durch, indem Sie im Terminal Folgendes eingeben:
+
`./wfa_ocsetup.sh JRE_path`

+
_JRE_PATH_ ist der Pfad zum JRE.

+
*Beispiel*

+
`/opt/NTAPdfm/java`

+
Die folgende Ausgabe wird auf dem Terminal angezeigt, was auf eine erfolgreiche Einrichtung hinweist:

+
[listing]
----
Verifying archive integrity... All good.
Uncompressing WFA OnCommand Setup.....
*** Welcome to OnCommand Setup Utility for Linux ***
    <Help information>
*** Please override the default credentials below ***
Override DB Username [wfa] :
----
. Geben Sie einen Benutzernamen und ein Kennwort ein, um die Standardanmeldeinformationen zu überschreiben.
+
Ein neues Datenbankbenutzerkonto wird mit Zugriff auf die Active IQ Data Center Manager Datenbank erstellt.

+

NOTE: Wenn Sie kein Benutzerkonto erstellen, werden die Standardanmeldeinformationen verwendet. Aus Sicherheitsgründen müssen Sie ein Benutzerkonto erstellen.

+
Die folgende Ausgabe wird auf dem Terminal angezeigt, was auf eine erfolgreiche Einrichtung hinweist:

+
[listing]
----
***** Start of response from the database *****
>>> Connecting to database
<<< Connected
*** Dropped existing 'wfa' user
=== Created user 'username'
>>> Granting access
<<< Granted access
***** End of response from the database *****
***** End of Setup *****
----

