---
permalink: windows-install/task-replace-the-default-workflow-automation-ssl-certificate.html 
sidebar: sidebar 
keywords: replace, default, workflow, automation, ssl, certificate 
summary: 'Sie können das Standard-SSL-Zertifikat der Workflow Automation (WFA) ersetzen, wenn das Zertifikat abgelaufen ist oder Sie die Gültigkeitsdauer des Zertifikats erhöhen möchten.' 
---
= Ersetzen Sie das Standard-SSL-Zertifikat der Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Standard-SSL-Zertifikat der Workflow Automation (WFA) ersetzen, wenn das Zertifikat abgelaufen ist oder Sie die Gültigkeitsdauer des Zertifikats erhöhen möchten.

.Was Sie benötigen
Sie müssen auf dem WFA Server über Windows-Administratorrechte verfügen.

.Über diese Aufgabe
In diesem Verfahren wird der WFA Standardinstallationspfad verwendet. Wenn Sie während der Installation den Standardspeicherort geändert haben, müssen Sie auch den benutzerdefinierten WFA Installationspfad verwenden.

.Schritte
. Melden Sie sich als Admin-Benutzer auf der WFA Host Machine an.
. Verwenden Sie die Windows Services-Konsole, um die folgenden WFA-Services zu beenden:
+
** NetApp WFA Datenbank
** NetApp WFA Server


. Löschen Sie die `wfa.keystore` Datei vom folgenden Speicherort: `<WFA_install_location>\WFA\jboss\standalone\configuration\keystore`
. Öffnen Sie eine Eingabeaufforderung auf dem WFA-Server, und ändern Sie das Verzeichnis in den folgenden Speicherort:
+
`<WFA_install_location>\WFA\jre\bin`

. Erhalten Sie den Datenbankschlüssel: `keytool -keysize 2048 -genkey -alias "ssl keystore" -keyalg RSA -keystore "<WFA_install_location>\WFA\jboss\standalone\configuration\keystore\wfa.keystore" -validity xxxx`
+
`xxxx` Gibt die Anzahl der Tage für die Gültigkeit des neuen Zertifikats an.

. Geben Sie bei der entsprechenden Aufforderung das Kennwort ein (Standard oder neu).
+
`changeit` Ist das Standardpasswort. Wenn Sie das Standardpasswort nicht verwenden möchten, müssen Sie das Passwortattribut des SSL-Elements im ändern `standalone-full.xml` Datei vom folgenden Speicherort: `<WFA_install_location>\WFA\jboss\standalone\configuration\`

+
*Beispiel*

+
[listing]
----
<ssl name="ssl" password="new_password" certificate-key-file="${jboss.server.config.dir}/keystore/wfa.keystore"
----
. Geben Sie die erforderlichen Details für das Zertifikat ein.
. Überprüfen Sie die angezeigten Informationen, und geben Sie ein `Yes`.
. Drücken Sie bei Aufforderung durch folgende Meldung die Eingabetaste*: `Enter key password for <SSL keystore> <RETURN if same as keystore password>.`
. Starten Sie die WFA Services über die Windows Services Konsole neu.

