---
permalink: windows-install/task-install-workflow-automation-on-windows.html 
sidebar: sidebar 
keywords: oncommand workflow automation, install, windows 
summary: 'Sie können OnCommand Workflow Automation (WFA) installieren, um Storage-Workflows zu erstellen und anzupassen und um die in Ihrer Umgebung ausgeführten Storage-Aufgaben zu automatisieren.' 
---
= Installieren Sie OnCommand Workflow Automation unter Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können OnCommand Workflow Automation (WFA) installieren, um Storage-Workflows zu erstellen und anzupassen und um die in Ihrer Umgebung ausgeführten Storage-Aufgaben zu automatisieren.

.Was Sie und#8217;ll benötigen
* Sie müssen die Installationsvoraussetzungen überprüft haben.
+
xref:reference-prerequisites-for-installing-workflow-automation.adoc[Voraussetzungen für die Installation von Workflow Automation]

* Wenn Sie WFA auf einem System installieren, auf dem WFA bereits installiert und dann deinstalliert wurde, müssen Sie sicherstellen, dass keine WFA Services auf diesem System vorhanden sind.
* Sie müssen das WFA Installationsprogramm von der NetApp Support Site heruntergeladen haben.
* Sie müssen das deaktivieren `Auto upgrade` Funktion von Java.


.Über diese Aufgabe
* Wenn Sie WFA auf einer virtuellen Maschine (VM) installieren, darf der Name der VM nicht das Unterstrich (_)-Zeichen enthalten.
* ActiveState ActivePerl ist vor der Installation von WFA installiert.
+
Diese Installation hat keine Auswirkung auf andere Instanzen von ActivePerl, die Sie auf Ihrem WFA Server installiert haben.

* Bevor Sie WFA 4.2 oder höher neu installieren, müssen Sie das MySQL-Datenverzeichnis löschen, wenn Sie MySQL deinstalliert haben.
* Wenn Sie MySQL selbst installieren, legt WFA die fest `secure-file-privilege` Und das `sql-mode` Eigenschaften in MySQL `my.ini` Leere Datei.


.Schritte
. Melden Sie sich unter Windows mit einem Konto mit Administratorberechtigungen an.
. Öffnen Sie den Windows Explorer, und navigieren Sie dann zum Verzeichnis, in dem sich die Installationsdatei befindet.
. WFA installieren:
+
** Interaktive Installation
+
... Klicken Sie mit der rechten Maustaste, und führen Sie die ausführbare Datei für den WFA Installer aus (`.exe`) Datei als Admin-Benutzer.
... Klicken Sie Auf *Weiter*.
... Geben Sie die Anmeldeinformationen für den Standard-Admin-Benutzer ein, und klicken Sie dann auf *Weiter*.
+
Das standardmäßige Admin-Passwort muss die folgenden Kriterien erfüllen:

+
**** Mindestens sechs Zeichen
**** Ein Großbuchstaben
**** Ein Kleinbuchstaben
**** Eine Ziffer
**** Ein Sonderzeichen *Hinweis:* Sie müssen die Anmeldedaten des Admin-Benutzers beachten.


... Wählen Sie die Ports für die WFA Konfiguration aus und klicken Sie dann auf *Weiter*.
... Geben Sie einen Standortnamen und Ihren Firmennamen ein, und klicken Sie dann auf *Weiter*.
+
Der Standortname kann den Standort der WFA Installation enthalten, z. B. Pittsburgh, PA.

... Wenn Sie den Standardinstallationsort ändern möchten, wählen Sie den Speicherort aus, an dem WFA installiert werden soll, und klicken Sie dann auf *Weiter*.
... Wenn Sie den Standardspeicherort der WFA-Datenbank nicht ändern möchten, klicken Sie auf *Weiter*.
... Klicken Sie auf *Installieren*, um mit der Installation fortzufahren.
... Klicken Sie auf *Fertig stellen*, um die Installation abzuschließen.
... Überprüfen Sie, ob WFA erfolgreich installiert wurde, indem Sie eine der folgenden Aktionen auswählen:
+
**** Zugriff auf WFA über einen Webbrowser
**** Überprüfen Sie mithilfe der Windows Services Konsole, ob der NetApp WFA Server Service und der NetApp WFA Database Service ausgeführt werden.




** Automatische Installation (über die Eingabeaufforderung): +
`WFA-version_number-build_number.exe /s /v"WFA_ADMIN_USERNAME=wfa_username WFA_ADMIN_PASSWORD=password WFA_ADMIN_CONFIRM_PASSWORD=confirm admin password / WFA_MYSQL_PASS=password CONFIRM_WFA_MYSQL_PASS=confirm MySQL password WFA_INSTALL_SITE=site WFA_INSTALL_ORGANIZATION=organization_name WFA_HTTP_PORT=port WFA_HTTPS_PORT=port INSTALLDIR=install_directory DATABASEDIR=database_directory /qr /l*v C:\install.log"`
+
*Beispiel*

+
`WFA-x64-v4.2.0.0.0-B2973881.exe /s /v"WFA_ADMIN_USERNAME=admin WFA_ADMIN_PASSWORD=Company*234 WFA_ADMIN_CONFIRM_PASSWORD=Company*234 WFA_MYSQL_PASS=MySQL*234 CONFIRM_WFA_MYSQL_PASS=MySQL*234 WFA_INSTALL_SITE=nb WFA_INSTALL_ORGANIZATION=netapp WFA_HTTP_PORT=9090 WFA_HTTPS_PORT=8443 INSTALLDIR=\"C:\Program Files\NetApp\WFA\" DATABASEDIR=\"C:\Program Files\NetApp\WFA\Database\" /qr /l*v C:\install.log"`

+

NOTE: Der `/qn` Option wird von WFA nicht unterstützt.

+
Die Befehlsparameter sind wie folgt:

+
[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
_WFA_ADMIN_USERNAME_
 a| 
Admin-Benutzername

Optionaler Parameter. Wenn Sie keinen Wert angeben, wird der Standardwert admin verwendet.



 a| 
_WFA_ADMIN_PASSWORD_
 a| 
Admin-Benutzer-Passwort

Obligatorischer Parameter. Das standardmäßige Admin-Passwort muss die folgenden Kriterien erfüllen:

*** Mindestens sechs Zeichen
*** Ein Großbuchstaben
*** Ein Kleinbuchstaben
*** Eine Ziffer
*** Ein Sonderzeichen




 a| 
_WFA_ADMIN_CONFIRM_PASSWORD_
 a| 
Admin-Benutzer-Passwort

Obligatorischer Parameter



 a| 
_WFA_MYSQL_PASS_
 a| 
MySQL-Benutzerpasswort

Obligatorischer Parameter



 a| 
_BESTÄTIGEN_WFA_MYSQL_PASS_
 a| 
MySQL-Benutzerpasswort

Obligatorischer Parameter



 a| 
_WFA_INSTALL_SITE_
 a| 
Organisationseinheit, in der WFA installiert ist obligatorisch



 a| 
_WFA_INSTALL_ORGANIZATION_
 a| 
Unternehmen oder Unternehmensname, in dem WFA installiert ist

Obligatorischer Parameter



 a| 
_WFA_HTTP_PORT_
 a| 
Optionaler HTTP-Port-Parameter. Wenn Sie keinen Wert angeben, wird der Standardwert 80 verwendet.



 a| 
_WFA_HTTPS_PORT_
 a| 
Optionaler HTTPS-Port-Parameter. Wenn Sie keinen Wert angeben, wird der Standardwert 443 verwendet.



 a| 
_INSTALLDIR_
 a| 
Pfad für das Installationsverzeichnis

Optionaler Parameter. Wenn Sie keinen Wert angeben, wird der Standardpfad verwendet `"C:\Program Files\NetApp\WFA\"` Verwendet wird.

|===




*Verwandte Informationen*

http://mysupport.netapp.com["NetApp Support"]
