---
permalink: windows-install/task-upgrade-jre-on-windows-wfa.html 
sidebar: sidebar 
keywords: oncommand workflow automation, upgrade, jre 
summary: 'Sie können neue Versionen der Java Runtime Environment (JRE) auf OnCommand Workflow Automation (WFA) auf dem Windows Server aktualisieren. Sie können ein Upgrade auf eine neuere Version von JRE durchführen, um die Behebung von Sicherheitsschwachstellen auf dem Windows-Server zu erhalten.' 
---
= Aktualisieren Sie JRE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können neue Versionen der Java Runtime Environment (JRE) auf OnCommand Workflow Automation (WFA) auf dem Windows Server aktualisieren. Sie können ein Upgrade auf eine neuere Version von JRE durchführen, um die Behebung von Sicherheitsschwachstellen auf dem Windows-Server zu erhalten.

Sie müssen auf dem WFA Server über Windows-Administratorrechte verfügen.

Sie können JRE-Versionen in Versionsfamilien aktualisieren. Sie können beispielsweise von Java 8 Update 144 (64 Bit) auf Java 8 Update 151 (64 Bit) aktualisieren, aber Sie können nicht direkt von Java 8 auf Java 9 aktualisieren.

.Schritte
. Melden Sie sich als Admin-Benutzer auf der WFA Host Machine an.
. Laden Sie die neueste Version von Java 8 64-Bit von der Oracle-Site auf das Zielsystem herunter, und installieren Sie sie.
. Verwenden Sie die Windows Services-Konsole, um die folgenden WFA-Services zu beenden:
+
** NetApp WFA Database oder MYSQL57
** NetApp WFA Server


. Klicken Sie Auf `updateWFARegistry.vbs` Von `<installdir>\WFA\bin\` Pfad zum Aktualisieren der neuesten JRE-Version in der WFA Registry.
+
*Beispiel*

+
[listing]
----
C:\Program Files\NetApp\WFA\bin>cscript.exe
updateWFARegistry.vbs
Microsoft (R) Windows Script Host Version 5.8
Copyright (C) Microsoft Corporation. All rights reserved
C:\Program Files\NetApp\WFA\bin>
----
. Starten Sie die WFA Services über die Windows Services Konsole.

