---
permalink: help/reference-clone-cache-query-dialog-box.html 
sidebar: sidebar 
keywords: clone cache query, dialog box 
summary: Im Dialogfeld „Cache-Abfrage bearbeiten“ können Sie eine Cache-Abfrage bearbeiten, die mit einem Glossareintrag verknüpft ist. 
---
= Dialogfeld „Clone Cache Query“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld „Cache-Abfrage bearbeiten“ können Sie eine Cache-Abfrage bearbeiten, die mit einem Glossareintrag verknüpft ist.

* *Wörterbuch-Eintrag*
+
Gibt einen Wörterbucheintrag an, der der Cache-Abfrage zugeordnet ist.

* *Entity Version*
+
Ermöglicht die Eingabe der Versionsnummer für die Cache-Abfrage im Format _major.minor.Revision_, z. B. 1.0.0.

* * Datenquellenarten*
+
Gibt den mit der Cache-Abfrage verknüpften Datenquellentyp an.





== Tabellenstruktur

Zeigt die Attribute und die SQL-Syntax an, die mit dem Glossareintrag verknüpft sind.

* *SQL Select query*
+
Gibt die SQL-Abfrage an, die mit dem Wörterbucheintrag und dem ausgewählten Datenanbietertyp verknüpft ist.





== Befehlsschaltflächen

* *Test*
+
Ermöglicht Ihnen das Testen der SQL-Abfrage, die im SQL Select-Abfragefeld eingegeben wurde.

* *Speichern*
+
Speichert die Cache-Abfrage als neuen Eintrag in der Tabelle Cache-Abfragen und schließt das Dialogfeld.

* *Abbrechen*
+
Bricht ggf. Änderungen ab und schließt das Dialogfeld.


