---
permalink: workflows/task-check-in-a-new-pack-to-scm.html 
sidebar: sidebar 
keywords: oncommand workflow automation, check, new, pack, scm 
summary: 'Sie können mit OnCommand Workflow Automation (WFA) ein neues Workflow-Paket erstellen und in Source Control Management (SCM) einchecken.' 
---
= Überprüfen Sie ein neues Workflow-Paket auf SCM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können mit OnCommand Workflow Automation (WFA) ein neues Workflow-Paket erstellen und in Source Control Management (SCM) einchecken.

SCM muss eingerichtet sein und Sie müssen über Administrator- oder Architekturdaten verfügen.

.Schritte
. Melden Sie sich über einen Webbrowser im *WFA*-Fenster an.
. Erstellen Sie ein neues Workflow-Paket.
+
link:task-create-a-workflow-automation-pack.html["Erstellen eines Workflow Automation Packs"]

. Fügen Sie dem erstellten Paket Entitäten hinzu.
+
link:task-add-entity-to-a-workflow-automation-pack.html["Fügen Sie Einheiten zu einem OnCommand Workflow Automation-Paket hinzu"]

. Klicken Sie auf das Symbol *Export to Server*.
. Geben Sie im Dialogfeld *in Serverordner exportieren* im Feld *Ordner-Speicherort am Serversystem* den Speicherort des Dateisystems ein, an dem das Paket auf dem Server gespeichert werden soll, der den SCM-Client enthält.
+
Um das Paket oder den Inhalt zu bearbeiten oder erneut zu exportieren, klicken Sie auf das Symbol *Entsperren*.

. Überprüfen Sie im SCM-Client den Inhalt des Packs auf dem SCM-Server.

